CREATE TABLE [dbo].[TB_ACOES](
	[IDACOES] [int] IDENTITY (1,1) PRIMARY KEY NOT NULL,
	[NMACOES] [varchar](50) NOT NULL,
	[QTDACOES] [int] NOT NULL,
	[VRMEDIO] [decimal](10, 2) NOT NULL,
	[VRATUAL] [decimal](10, 2) NOT NULL,
	[VRANTERIOR] [decimal](10, 2) NULL,
	[DTATUALIZACAO] [datetime] NULL,
) 
GO





CREATE TABLE [dbo].[TB_CMP_ACOES](
	[IDCMPACOES] [int] IDENTITY (1,1)PRIMARY KEY NOT NULL,
	[IDACOES] [int] NOT NULL,
	[DTCMP] [datetime] NOT NULL,
	[VRCMP] [decimal](10, 2) NOT NULL,
	[NMCORRETORA] [varchar](50) NOT NULL)
GO

ALTER TABLE [dbo].[TB_CMP_ACOES]  WITH CHECK ADD  CONSTRAINT [FK_AcaoCompra] FOREIGN KEY([IDACOES])
REFERENCES [dbo].[TB_ACOES] ([IDACOES])
GO

ALTER TABLE [dbo].[TB_CMP_ACOES] CHECK CONSTRAINT [FK_AcaoCompra]
GO


CREATE TABLE [dbo].[TB_HIST_PRECO](
	[IDHIST] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[IDACOES] [int] NOT NULL,
	[DTHORA] [datetime] NOT NULL,
	[VRPRECO] [decimal](10, 2) NOT NULL
) 
GO

ALTER TABLE [dbo].[TB_HIST_PRECO] ADD  DEFAULT (getdate()) FOR [DTHORA]
GO

